2019-03-31 11:32:54,859 ERROR: Exception on /user/susan [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 108, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/python/workspace/microblog/app/templates/base.html", line 31, in top-level template code
    {% block content %}
  File "/home/python/workspace/microblog/app/templates/user.html", line 14, in block "content"
    {% elif not current_user.is_following(user) %}
UndefinedError: 'app.models.User object' has no attribute 'is_following'
2019-03-31 11:34:42,919 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:54]
