2019-04-01 15:40:37,432 ERROR: Exception on /unfollow/aaajjj1627 [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 175, in unfollow
    flash(_('You are not following %(username).',username=username))
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_babel/__init__.py", line 556, in gettext
    return s if not variables else s % variables
ValueError: unsupported format character '?' (0xff01) at index 16
2019-04-01 15:44:05,750 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:68]
2019-04-01 15:45:31,034 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:68]
