2019-03-31 17:06:01,379 ERROR: Exception on /index [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 37, in index
    prev_url=prev_url)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/index.html", line 24, in template
    <a href="{{ next_url or '#' }}">
TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2019-03-31 17:07:31,707 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:53]
2019-03-31 17:18:07,683 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:53]
2019-03-31 17:38:58,678 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:56]
2019-03-31 17:40:05,303 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:56]
2019-03-31 17:40:51,779 ERROR: Exception on /user/aaajjj1627 [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 132, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/python/workspace/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 7, in block "head"
    <title>{% block title %}{{title|default}}{% endblock title %}</title>
  File "/home/python/workspace/microblog/app/templates/base.html", line 4, in block "title"
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
UndefinedError: '_' is undefined
2019-03-31 17:40:57,559 ERROR: Exception on /user/aaajjj1627 [GET] [in /home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/python/workspace/microblog/app/routes.py", line 132, in user
    next_url=next_url, prev_url=prev_url)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/python/workspace/microblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/python/workspace/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 6, in block "html"
    {%- block head %}
  File "/home/python/.virtualenvs/flask/local/lib/python2.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 7, in block "head"
    <title>{% block title %}{{title|default}}{% endblock title %}</title>
  File "/home/python/workspace/microblog/app/templates/base.html", line 4, in block "title"
    {% if title %}{{ title }} - Microblog{% else %}{{ _('Welcome to Microblog') }}{% endif %}
UndefinedError: '_' is undefined
2019-03-31 17:41:51,514 INFO: Microblog startup [in /home/python/workspace/microblog/app/__init__.py:56]
